# ===============================
# APPLICATION
# ===============================
spring.application.name=doctor-appointment-system

# ===============================
# MONGODB
# ===============================
spring.data.mongodb.uri=mongodb://localhost:27017/doctor_appointment_system

# ===============================
# SERVER (optional ali preporu?eno)
# ===============================
server.port=8080

# ===============================
# SWAGGER / SPRINGDOC UI
# ===============================
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.doc-expansion=none
springdoc.swagger-ui.defaultModelsExpandDepth=-1
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.filter=true

# (opciono - malo moderniji izgled)
springdoc.swagger-ui.syntaxHighlight.theme=monokai


springdoc.swagger-ui.persist-authorization=true
springdoc.swagger-ui.enable-copy=true


springdoc.swagger-ui.syntaxHighlight.activated=true
springdoc.swagger-ui.defaultModelExpandDepth=-1
